/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ConsoleApplication1
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TTest : TBase
  {
    private string _mekker;
    private int _numberOfTimes;

    public string Mekker
    {
      get
      {
        return _mekker;
      }
      set
      {
        __isset.mekker = true;
        this._mekker = value;
      }
    }

    public int NumberOfTimes
    {
      get
      {
        return _numberOfTimes;
      }
      set
      {
        __isset.numberOfTimes = true;
        this._numberOfTimes = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool mekker;
      public bool numberOfTimes;
    }

    public TTest() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.String) {
              Mekker = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.I32) {
              NumberOfTimes = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TTest");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Mekker != null && __isset.mekker) {
        field.Name = "mekker";
        field.Type = TType.String;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Mekker);
        oprot.WriteFieldEnd();
      }
      if (__isset.numberOfTimes) {
        field.Name = "numberOfTimes";
        field.Type = TType.I32;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(NumberOfTimes);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TTest(");
      sb.Append("Mekker: ");
      sb.Append(Mekker);
      sb.Append(",NumberOfTimes: ");
      sb.Append(NumberOfTimes);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
